name: main

permissions:
  contents: write

on:

  push:
    branches: [ master, include-windows-in-ci-cd]
    tags: [ "*" ]
    paths-ignore: [ "*.md" ]

  pull_request:
    branches: [ master ]

jobs:

  build-test-package:
    name: Build/Test/Package
    uses: ./.github/workflows/build-test.yml
